name: Release Please

on:
  push:
    branches: [main]

jobs:
  reusable:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: groundsgg/.github/.github/workflows/release-please.yml@main
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
